export const GET_RECIPES = 'Recipes/GET_RECIPES';

export const GET_RECIPES_REQUEST = 'Recipes/GET_RECIPES_REQUEST';
export const GET_RECIPES_SUCCESS = 'Recipes/GET_RECIPES_SUCCESS';
export const GET_RECIPES_ERROR = 'Recipes/GET_RECIPES_ERROR';
export const GET_RECIPES_DELETE = 'Recipes/GET_RECIPES_DELETE';