export const DELETE_RATING_REQUEST = "Rating/DELETE_RATING_REQUEST";
export const DELETE_RATING_SUCCESS = "Rating/DELETE_RATING_SUCCESS";
export const DELETE_RATING_ERROR = "Rating/DELETE_RATING_ERROR";