export const DELETE_COMMENT_REQUEST = 'Comment/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'Comment/DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'Comment/DELETE_COMMENT_ERROR';