export const UPDATE_COMMENT_REQUEST = 'Comment/UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'Comment/UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_ERROR = 'Comment/UPDATE_COMMENT_ERROR';