export const COMMENT = 'Comment/COMMENT';

export const ADD_COMMENT_REQUEST = 'Comment/ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'Comment/ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'Comment/ADD_COMMENT_ERROR';
export const ADD_COMMENT_DELETE = 'Comment/ADD_COMMENT_DELETE';

export const UPDATE_COMMENT_REQUEST = 'Comment/UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'Comment/UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_ERROR = 'Comment/UPDATE_COMMENT_ERROR';
export const UPDATE_COMMENT_DELETE = 'Comment/UPDATE_COMMENT_DELETE';

export const DELETE_COMMENT_REQUEST = 'Comment/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'Comment/DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'Comment/DELETE_COMMENT_ERROR';
export const DELETE_COMMENT_DELETE = 'Comment/DELETE_COMMENT_DELETE';