export const DELETE_RECIPE_REQUEST = "Recipe/DELETE_RECIPE_REQUEST";
export const DELETE_RECIPE_SUCCESS = "Recipe/DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_ERROR = "Recipe/DELETE_RECIPE_ERROR";