export const UPDATE_INGREDIENTS_REQUEST = 'Recipe/UPDATE_INGREDIENTS_REQUEST';
export const UPDATE_INGREDIENTS_SUCCESS = 'Recipe/UPDATE_INGREDIENTS_SUCCESS';
export const UPDATE_INGREDIENTS_ERROR = 'Recipe/UPDATE_INGREDIENTS_ERROR';