export const UPDATE_DIRECTIONS_REQUEST = 'Recipe/UPDATE_DIRECTIONS_REQUEST';
export const UPDATE_DIRECTIONS_SUCCESS = 'Recipe/UPDATE_DIRECTIONS_SUCCESS';
export const UPDATE_DIRECTIONS_ERROR = 'Recipe/UPDATE_DIRECTIONS_ERROR';