export const UPDATE_RECIPE_REQUEST = 'Recipe/UPDATE_RECIPE_REQUEST';
export const UPDATE_RECIPE_SUCCESS = 'Recipe/UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_ERROR = 'Recipe/UPDATE_RECIPE_ERROR';