export const ADD_RECIPE_REQUEST = 'Recipe/ADD_RECIPE_REQUEST';
export const ADD_RECIPE_SUCCESS = 'Recipe/ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_ERROR = 'Recipe/ADD_RECIPE_ERROR';

export const ADD_PHOTO_REQUEST = 'Recipe/ADD_PHOTO_REQUEST';
export const ADD_PHOTO_SUCCESS = 'Recipe/ADD_PHOTO_SUCCESS';
export const ADD_PHOTO_ERROR = 'Recipe/ADD_PHOTO_ERROR';

export const ADD_INGREDIENTS_REQUEST = 'Recipe/ADD_INGREDIENTS_REQUEST';
export const ADD_INGREDIENTS_SUCCESS = 'Recipe/ADD_INGREDIENTS_SUCCESS';
export const ADD_INGREDIENTS_ERROR = 'Recipe/ADD_INGREDIENTS_ERROR';

export const ADD_DIRECTIONS_REQUEST = 'Recipe/ADD_DIRECTIONS_REQUEST';
export const ADD_DIRECTIONS_SUCCESS = 'Recipe/ADD_DIRECTIONS_SUCCESS';
export const ADD_DIRECTIONS_ERROR = 'Recipe/ADD_DIRECTIONS_ERROR';

export const ADD_HINTS_REQUEST = 'Recipe/ADD_HINTS_REQUEST';
export const ADD_HINTS_SUCCESS = 'Recipe/ADD_HINTS_SUCCESS';
export const ADD_HINTS_ERROR = 'Recipe/ADD_HINTS_ERROR';

export const ADD_TAGS_REQUEST = 'Recipe/ADD_TAGS_REQUEST';
export const ADD_TAGS_SUCCESS = 'Recipe/ADD_TAGS_SUCCESS';
export const ADD_TAGS_ERROR = 'Recipe/ADD_TAGS_ERROR';


export const UPDATE_RECIPE_REQUEST = 'Recipe/UPDATE_RECIPE_REQUEST';
export const UPDATE_RECIPE_SUCCESS = 'Recipe/UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_ERROR = 'Recipe/UPDATE_RECIPE_ERROR';

export const UPDATE_PHOTO_REQUEST = 'Recipe/UPDATE_PHOTO_REQUEST';
export const UPDATE_PHOTO_SUCCESS = 'Recipe/UPDATE_PHOTO_SUCCESS';
export const UPDATE_PHOTO_ERROR = 'Recipe/UPDATE_PHOTO_ERROR';

export const UPDATE_INGREDIENTS_REQUEST = 'Recipe/UPDATE_INGREDIENTS_REQUEST';
export const UPDATE_INGREDIENTS_SUCCESS = 'Recipe/UPDATE_INGREDIENTS_SUCCESS';
export const UPDATE_INGREDIENTS_ERROR = 'Recipe/UPDATE_INGREDIENTS_ERROR';

export const UPDATE_DIRECTIONS_REQUEST = 'Recipe/UPDATE_DIRECTIONS_REQUEST';
export const UPDATE_DIRECTIONS_SUCCESS = 'Recipe/UPDATE_DIRECTIONS_SUCCESS';
export const UPDATE_DIRECTIONS_ERROR = 'Recipe/UPDATE_DIRECTIONS_ERROR';

export const UPDATE_HINTS_REQUEST = 'Recipe/UPDATE_HINTS_REQUEST';
export const UPDATE_HINTS_SUCCESS = 'Recipe/UPDATE_HINTS_SUCCESS';
export const UPDATE_HINTS_ERROR = 'Recipe/UPDATE_HINTS_ERROR';
