export const UPDATE_RECIPE = 'Recipe/UPDATE_RECIPE';

export const UPDATE_RECIPE_REQUEST = 'Recipe/UPDATE_RECIPE_REQUEST';
export const UPDATE_RECIPE_SUCCESS = 'Recipe/UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_ERROR = 'Recipe/UPDATE_RECIPE_ERROR';
export const UPDATE_RECIPE_DELETE = 'Recipe/UPDATE_RECIPE_DELETE';

export const UPDATE_INGREDIENTS_REQUEST = 'Recipe/UPDATE_INGREDIENTS_REQUEST';
export const UPDATE_INGREDIENTS_SUCCESS = 'Recipe/UPDATE_INGREDIENTS_SUCCESS';
export const UPDATE_INGREDIENTS_ERROR = 'Recipe/UPDATE_INGREDIENTS_ERROR';
export const UPDATE_INGREDIENTS_DELETE = 'Recipe/UPDATE_INGREDIENTS_DELETE';

export const UPDATE_DIRECTIONS_REQUEST = 'Recipe/UPDATE_DIRECTIONS_REQUEST';
export const UPDATE_DIRECTIONS_SUCCESS = 'Recipe/UPDATE_DIRECTIONS_SUCCESS';
export const UPDATE_DIRECTIONS_ERROR = 'Recipe/UPDATE_DIRECTIONS_ERROR';
export const UPDATE_DIRECTIONS_DELETE = 'Recipe/UPDATE_DIRECTIONS_DELETE';

export const UPDATE_HINTS_REQUEST = 'Recipe/UPDATE_HINTS_REQUEST';
export const UPDATE_HINTS_SUCCESS = 'Recipe/UPDATE_HINTS_SUCCESS';
export const UPDATE_HINTS_ERROR = 'Recipe/UPDATE_HINTS_ERROR';
export const UPDATE_HINTS_DELETE = 'Recipe/UPDATE_HINTS_DELETE';

export const UPDATE_PHOTO_REQUEST = 'Recipe/UPDATE_PHOTO_REQUEST';
export const UPDATE_PHOTO_SUCCESS = 'Recipe/UPDATE_PHOTO_SUCCESS';
export const UPDATE_PHOTO_ERROR = 'Recipe/UPDATE_PHOTO_ERROR';
export const UPDATE_PHOTO_DELETE = 'Recipe/UPDATE_PHOTO_DELETE';