export const ADD_DIRECTIONS_REQUEST = 'Recipe/ADD_DIRECTIONS_REQUEST';
export const ADD_DIRECTIONS_SUCCESS = 'Recipe/ADD_DIRECTIONS_SUCCESS';
export const ADD_DIRECTIONS_ERROR = 'Recipe/ADD_DIRECTIONS_ERROR';