export const ADD_INGREDIENTS_REQUEST = 'Recipe/ADD_INGREDIENTS_REQUEST';
export const ADD_INGREDIENTS_SUCCESS = 'Recipe/ADD_INGREDIENTS_SUCCESS';
export const ADD_INGREDIENTS_ERROR = 'Recipe/ADD_INGREDIENTS_ERROR';